#!/usr/bin/sh
# Cursor theme
riverctl xcursor-theme Bibata-Original-Classic 24


# Gsettings set
riverctl spawn 'gsettings set org.gnome.desktop.interface gtk-theme "Orchis-Dark"'
riverctl spawn 'gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"'
riverctl spawn 'gsettings set org.gnome.desktop.interface cursor-theme "Bibata-Original-Classic"'
riverctl spawn 'gsettings set org.gnome.desktop.interface cursor-size "24"'
riverctl spawn 'gsettings set org.gnome.desktop.interface document-font-name "Serif 9"'
riverctl spawn 'gsettings set org.gnome.desktop.interface font-name "Sans Serif 9"'
riverctl spawn 'gsettings set org.gnome.desktop.interface monospace-font-name "monospace 8"'
riverctl spawn 'gsettings set org.gnome.desktop.interface font-antialiasing "rgba"'
riverctl spawn 'gsettings set org.gnome.desktop.interface font-hinting "full"'
riverctl spawn 'gsettings set org.gnome.desktop.interface text-scaling-factor "1.25"'
riverctl spawn 'gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:"'


# Autostart
riverctl spawn 'foot -s'
riverctl spawn 'ryzenadj -f 75'
riverctl spawn 'mako'
riverctl spawn 'waybar -c $HOME/.config/waybar/Sahara/river.jsonc -s $HOME/.config/waybar/Sahara/style.css -l warning'
riverctl spawn 'wl-paste --watch cliphist -max-items 36 store'
riverctl spawn '/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1'
riverctl spawn 'swaybg -i $HOME/.local/share/wallpapers/01.jpg -m fill'
riverctl spawn '/usr/lib/xdg-desktop-portal-wlr'
riverctl spawn '/usr/lib/xdg-desktop-portal-gtk'


# Border
riverctl border-color-focused 0xFFB785
riverctl border-color-unfocused 0x4d4541


# Key Binding
riverctl map normal Super Return spawn 'footclient'
riverctl map normal Super D spawn 'rofi -show drun -config $HOME/.config/rofi/Sahara/Sahara.rasi'
riverctl map normal Super+Shift R spawn 'pkexec reboot'
riverctl map normal Super+Shift P spawn 'pkexec poweroff'
riverctl map normal None Print spawn 'grim $HOME/Pictures/screen-"$(date +%s)".png'
riverctl map normal Super Print spawn 'grim -g "$(slurp)" $HOME/Pictures/screen-"$(date +%s)".png'

riverctl map normal Super Q close
riverctl map normal Super+Shift E exit
riverctl map normal Super+Shift F toggle-fullscreen
riverctl map normal Super F toggle-float


# Workspaces
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
done
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags


# Movement
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

riverctl map -repeat normal Super H send-layout-cmd rivertile "main-ratio -0.02"
riverctl map -repeat normal Super L send-layout-cmd rivertile "main-ratio +0.02"

riverctl map -repeat normal Super+Alt H move left 30
riverctl map -repeat normal Super+Alt J move down 30
riverctl map -repeat normal Super+Alt K move up 30
riverctl map -repeat normal Super+Alt L move right 30

riverctl map -repeat normal Super+Alt+Shift H resize horizontal -30
riverctl map -repeat normal Super+Alt+Shift J resize vertical 30
riverctl map -repeat normal Super+Alt+Shift K resize vertical -30
riverctl map -repeat normal Super+Alt+Shift L resize horizontal 30

riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"


# Input devices
riverctl keyboard-layout -options grp:caps_toggle us,ua
riverctl input pointer-1133-49284-Logitech_G102_Prodigy_Gaming_Mouse accel-profile flat
riverctl input pointer-1267-12541-ELAN0718:00_04F3:30FD_Touchpad tap enabled

riverctl set-repeat 30 300


# Fn keys
for mode in normal locked
do
	riverctl map -repeat $mode None XF86AudioRaiseVolume	spawn 'wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%+'
	riverctl map -repeat $mode None XF86AudioLowerVolume	spawn 'wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%-'
	riverctl map $mode None XF86AudioMute									spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'

	riverctl map $mode None XF86AudioPlay									spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPrev									spawn 'playerctl previous'
	riverctl map $mode None XF86AudioNext									spawn 'playerctl next'

	riverctl map -repeat $mode None XF86MonBrightnessUp		spawn 'brightnessctl set 2%+'
	riverctl map -repeat $mode None XF86MonBrightnessDown	spawn 'brightnessctl set 2%-'
done


# Rules
riverctl rule-add -app-id '*' ssd
riverctl rule-add -app-id "bar" csd
riverctl rule-add -app-id 'swayimg' float


# Layout
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 2 &
